### ISSUE TITLE
Drag and Drop not working in Debian

### ISSUE THREAD

**Issue by maximelucas** [luphysics/PyMODA#8]
To load a file, drag and drop is not working: when dropping, the file is not selected. Nothing happens apart from the background of the drag and drop window blinking in dark grey when dropping.

OS: Debian GNU/Linux bullseye/sid, with GNOME 3.34.2
Python: 3.7.6

**Comment by spmccormack** [comment]
Thanks for the info. Just to check, are you using Git to update to the new version, or the built-in updater?

**Comment by maximelucas** [comment]
I've only used the built-in updater, seems to work very well.
My Debian is another machine than my Ubuntu though: I just freshly installed pyMODA on Debian today after you solved the last issues.

**Comment by spmccormack** [comment]
Thanks, it's good to have feedback on the updater! 

The updater downloads updates from the `release` branch, and I'd forgotten to push the changes to that branch. You may have downloaded the new version from the `release` branch too, since that's what the download link in the User Guide points to.

Just to double-check that we're on the same codebase, could you try updating the Debian version? If you force a check for updates by pressing `Ctrl`+`U` (or maybe `Cmd`+`U` on Mac) while the launcher window is active, it should print a message and show the update button.

**Comment by spmccormack** [comment]
(Just in case your version wasn't detecting an update: as of 2 minutes ago, you should definitely be able to detect an update when you use the `Ctrl`+`U` shortcut.)

**Comment by maximelucas** [comment]
I've now updated on Debian (the problem persists).

**Comment by spmccormack** [comment]
> I've now updated on Debian (the problem persists).

Ok, thanks for clarifying! I'll set up a virtual machine and test it myself. Which desktop environment are you using on Debian, is it GNOME?

In general, drag-and-drop seems a bit flaky on Linux; with KDE Plasma it doesn't work at all, with GNOME on Ubuntu it works (since the fix this morning) and I haven't tested any other desktop environments.

**Comment by maximelucas** [comment]
I'm using GNOME 3.34.2 on Debian.

No worries, it's not a crucial issue, as loading via direct browsing works anyway. It's just so you know!

**Comment by spmccormack** [comment]
I've tested drag-and-drop with GNOME 3.30.2 on Debian, and for some reason it works fine. 

Perhaps the problem was introduced in a newer version of GNOME; there's probably not much that can be done, so I'll close this issue. Thanks for the feedback though!
